name: Deploy Fullstack App to Azure VM

on:
  push:
    branches:
      - new-demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/proshop-v2

            git pull origin new-demo

            cd backend
            npm install

            cd ../frontend
            npm install

            /usr/bin/pm2 restart backend
            /usr/bin/pm2 restart frontend
